language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
install: "pip install http://github.com/tBaxter/django-voting/tarball/master#egg=tango-voting --editable ."
script: django-admin.py test --settings=test_settings
